version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodata:/data/db
    networks:
      - mern-network

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: ${DATABASE_URI_DOCKER}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    depends_on:
      - mongo_db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo_db:
